apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.env.name }}-certificate"
  namespace: {{ .Values.env.namespace.field }}
spec:
  secretName: "{{ .Values.env.name }}-certs"
  dnsNames:
  - "{{ .Values.env.service }}"
  - "{{ .Values.env.service }}.{{ .Values.env.namespace.field }}"
  - "{{ .Values.env.service }}.{{ .Values.env.namespace.field }}.svc"
  issuerRef:
    name: "selfsigned-{{ .Values.env.name }}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "domino-field"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "domino-compute" # Control auto-reflection namespaces
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "selfsigned-{{ .Values.env.name }}"
spec:
  selfSigned: {}