apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.env.name }}"
  namespace: "{{ .Values.env.namespace.field }}"
rules:
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "get"
  - "update"
  - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.env.name }}"
  namespace: "{{ .Values.env.namespace.compute }}"
rules:
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  verbs:
  - "get"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"

