apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.env.name }}
  namespace: {{ .Values.env.namespace.field }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.env.eks_aws_account }}:role/{{ .Values.env.eks_service_role_name }}