apiVersion: v1
items:
- apiVersion: apps.dominodatalab.com/v1alpha1
  kind: Mutation
  metadata:
    annotations:
      meta.helm.sh/release-name: irsa
      meta.helm.sh/release-namespace: domino-field
    creationTimestamp: "2023-08-23T15:58:46Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: irsa
    namespace: domino-platform
    resourceVersion: "220266897"
    uid: f94694fd-7f6c-415b-b9f0-578af5ae2295
  rules:
  - labelSelectors:
    - app.kubernetes.io/name in (spark,ray,dask)
    matchBuilds: false
    modifyLabel:
      key: dominodatalab.com/workload-type
      value: cluster
  - labelSelectors:
    - dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)
    matchBuilds: false
    modifySecurityContext:
      context:
        fsGroup: 12574
  - insertContainer:
      containerType: app
      spec:
        image: quay.io/domino/irsa-client:v1.0.0-release
        imagePullPolicy: Always
        name: aws-config-file-generator
    labelSelectors:
    - dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)
    matchBuilds: false
  - insertVolumeMounts:
      containerSelector:
      - aws-config-file-generator
      volumeMounts:
      - mountPath: /var/run/podinfo
        name: podinfo
        readOnly: true
      - mountPath: /var/log/irsa
        name: irsa-logs
    labelSelectors:
    - dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)
    matchBuilds: false
  - insertVolumes:
    - emptyDir:
        sizeLimit: 1000Mi
      name: irsa-logs
    - emptyDir:
        sizeLimit: 500Mi
      name: aws-config-file
    - downwardAPI:
        items:
        - fieldRef:
            fieldPath: metadata.labels
          path: labels
      name: podinfo
    - name: aws-user-token
      projected:
        defaultMode: 422
        sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token
    labelSelectors:
    - dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)
    matchBuilds: false
  - insertVolumeMounts:
      containerSelector:
      - run
      volumeMounts:
      - mountPath: /var/run/.aws
        name: aws-config-file
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount/
        name: aws-user-token
        readOnly: true
      - mountPath: /var/log/irsa
        name: irsa-logs
        readOnly: true
      - mountPath: /var/run/podinfo
        name: podinfo
        readOnly: true
    labelSelectors:
    - dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)
    matchBuilds: false
  - insertVolumeMounts:
      containerSelector:
      - aws-config-file-generator
      volumeMounts:
      - mountPath: /var/run/.aws
        name: aws-config-file
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount/
        name: aws-user-token
        readOnly: true
      - mountPath: /var/run/podinfo
        name: podinfo
        readOnly: true
    labelSelectors:
    - dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)
    matchBuilds: false
  - labelSelectors:
    - dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)
    matchBuilds: false
    modifyEnv:
      containerSelector:
      - aws-config-file-generator
      env:
      - name: POD_INFO_PATH
        value: /var/run/podinfo/labels
      - name: DOMINO_API_PROXY
        value: http://localhost:8899
  - labelSelectors:
    - dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)
    matchBuilds: false
    modifyEnv:
      containerSelector:
      - run
      - aws-config-file-generator
      env:
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      - name: AWS_CONFIG_FILE
        value: /var/run/.aws/config
      - name: DOMINO_IRSA_ENDPOINT
        value: http://irsa-svc.domino-field/map_iam_roles_to_pod_sa
      - name: DOMINO_API_PROXY
        value: http://localhost:8899
- apiVersion: apps.dominodatalab.com/v1alpha1
  kind: Mutation
  metadata:
    annotations:
      meta.helm.sh/release-name: jit-ddl-field
      meta.helm.sh/release-namespace: domino-field
    creationTimestamp: "2023-08-22T20:14:05Z"
    generation: 25
    labels:
      app.kubernetes.io/managed-by: Helm
    name: jit
    namespace: domino-platform
    resourceVersion: "232929757"
    uid: 7816be87-dfca-464a-9ea5-94c06aadc111
  rules:
  - insertContainer:
      containerType: app
      spec:
        image: quay.io/domino/field/jit-client:mdoan.PS-8197
        imagePullPolicy: Always
        name: jit
        volumeMounts:
        - mountPath: /var/log/jit/
          name: log-volume
        - mountPath: /etc/.aws/
          name: jit-aws-creds
    insertVolumeMounts:
      containerSelector:
      - run
      volumeMounts:
      - mountPath: /var/log/jit/
        name: log-volume
        readOnly: true
      - mountPath: /etc/.aws/
        name: jit-aws-creds
        readOnly: true
    insertVolumes:
    - emptyDir: {}
      name: jit-aws-creds
    - emptyDir: {}
      name: log-volume
    labelSelectors:
    - dominodatalab.com/workload-type in (Workspace)
    - dominodatalab.com/starting-user-username in (marc_doan)
    matchBuilds: false
    modifyEnv:
      containerSelector:
      - jit
      env:
      - name: AWS_SHARED_CREDENTIALS_FILE
        value: /etc/.aws/credentials
      - name: DOMINO_JIT_ENDPOINT
        value: http://jit-svc.domino-field/jit-sessions
      - name: DOMINO_API_PROXY
        value: http://localhost:8899
      - name: DOMINO_JIT_REFRESH_ENDPOINT
        value: 'http://localhost:'
- apiVersion: apps.dominodatalab.com/v1alpha1
  kind: Mutation
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps.dominodatalab.com/v1alpha1","kind":"Mutation","metadata":{"annotations":{},"name":"modify-sec-cont","namespace":"domino-platform"},"rules":[{"labelSelectors":["dominodatalab.com/workload-engine==cg2"],"modifySecurityContext":{"context":{"capabilities":{"add":["AUDIT_WRITE"]}}}}]}
    creationTimestamp: "2023-09-01T13:29:00Z"
    generation: 4
    name: modify-sec-cont
    namespace: domino-platform
    resourceVersion: "226015746"
    uid: e3ed5667-6f18-48c3-9963-74c8145b1f4e
  rules:
  - labelSelectors:
    - dominodatalab.com/workload-engine==cg2
    matchBuilds: false
    modifySecurityContext:
      context:
        capabilities:
          add:
          - AUDIT_WRITE
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
