apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  annotations:
    meta.helm.sh/release-name: irsa
    meta.helm.sh/release-namespace: domino-field
  labels:
    app.kubernetes.io/managed-by: Helm
  name: irsa
  namespace: domino-platform
rules:
- labelSelectors:
  - app.kubernetes.io/name in (spark,ray,dask)
  matchBuilds: false
  modifyLabel:
    key: dominodatalab.com/workload-type
    value: cluster
- insertContainer:
    containerType: app
    spec:
      env:
      - name: POD_INFO_PATH
        value: /var/run/podinfo/labels
      - name: DOMINO_API_PROXY
        value: http://localhost:8899
      image: quay.io/domino/irsa-client:v1.1.0-release
      imagePullPolicy: Always
      name: aws-config-file-generator
      volumeMounts:
      - mountPath: /var/run/.aws
        name: aws-config-file
      - mountPath: /var/log/irsa
        name: irsa-logs
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount/
        name: aws-user-token
        readOnly: true
      - mountPath: /var/run/podinfo
        name: podinfo
        readOnly: true
      - mountPath: /etc/ssl/certs/irsa
        name: irsa-ssl-certs
        readOnly: true
  insertVolumes:
  - name: irsa-ssl-certs
    secret:
      secretName: irsa-certs
  - emptyDir:
      sizeLimit: 1000Mi
    name: irsa-logs
  - emptyDir:
      sizeLimit: 500Mi
    name: aws-config-file
  - downwardAPI:
      items:
      - fieldRef:
          fieldPath: metadata.labels
        path: labels
    name: podinfo
  - name: aws-user-token
    projected:
      defaultMode: 422
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
  labelSelectors:
  - dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)
  matchBuilds: false
  modifySecurityContext:
    context:
      fsGroup: 12574
- insertVolumeMounts:
    containerSelector:
    - run
    volumeMounts:
    - mountPath: /var/run/.aws
      name: aws-config-file
      readOnly: true
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount/
      name: aws-user-token
      readOnly: true
    - mountPath: /var/log/irsa
      name: irsa-logs
      readOnly: true
    - mountPath: /var/run/podinfo
      name: podinfo
      readOnly: true
    - mountPath: /etc/ssl/certs/irsa
      name: irsa-ssl-certs
      readOnly: true
  labelSelectors:
  - dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)
  matchBuilds: false
  modifyEnv:
    containerSelector:
    - run
    - aws-config-file-generator
    env:
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    - name: AWS_CONFIG_FILE
      value: /var/run/.aws/config
    - name: DOMINO_IRSA_ENDPOINT
      value: https://irsa-svc.domino-field/map_iam_roles_to_pod_sa
    - name: AWS_DEFAULT_REGION
      value: us-west-2
    - name: AWS_REGION
      value: us-west-2
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
    - name: OIDC_PROVIDER
      value: oidc.eks.us-west-2.amazonaws.com/id/D24BE61D3A9AFFB8DBACFA731B2B277C
    - name: OIDC_PROVIDER_AUDIENCE
      value: sts.amazonaws.com
    - name: DOMINO_IRSA_PROXY
      value: http://localhost:6003
    - name: DOMINO_IRSA_SSL_CERT
      value: /etc/ssl/certs/irsa/tls.crt
